# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ed09283f103542804a3cc6e11962a3a1ad9033bc2e695399626b5f2de0a331d7cf5372b92b18a369561ffcfc867f4ce426127f6233d55c6bfbfcfacc50ab30d

test:
  secret_key_base: d6780052032d8f119025446515c3b55320b8fafcf645bf8f6132473d9fbcc3bec6a49c1ea720e1633e20308c7eb0c9bf80c8d99de4688b6663f4570bd42745ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
